### ISSUE TITLE
Data Fusion from Multiple Occupancy Grids

### ISSUE THREAD

**Issue by mistryrakesh** [Innovation-Cell/Issue-Tracking#2]
Create a single probabilistic occupancy grid from multiple occupancy grids keeping into account probability distribution in every map and different map sizes.

**Comment by kishore19a** [comment]
problem statement -- data fusion of 2 probabilistic maps of different size, resolution, frequency, etc.
get papers from  -  rakesh
talk to prof. nair(elec. dept.)

**Comment by kishore19a** [comment]
Rakesh, Make Mohit Chabra also a participant in this issue....his username on github is : iammohitchhabra

**Comment by mistryrakesh** [comment]
I saw this introductory paper on sensor data fusion: [An introduction to multisensor data fusion](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=554205)

**Comment by iammohitchhabra** [comment]
Please see this document. Looks relevant and may be easy to implement.
http://www.robots.ox.ac.uk/~az/lectures/est/lect34.pdf

**Comment by kishore19a** [comment]
karte hai implement

**Comment by kishore19a** [comment]
http://www.hindawi.com/journals/tswj/2013/704504/

ek baar is article ko bhi padhh ligiyega mohit

**Comment by mistryrakesh** [comment]
Hey Parth, you may also want to look at this. **Section 3** talks about data association using PDA and JPDA.

**Comment by kishore19a** [comment]
Mohit ... the article you shared is good for very idealistic situation and
not particularly serves our purpose....doesn't keep track of different grid
size, temporal and spacial data alignment, association and tracking.,, and
other paper which I have shared is quite computationally intensive, needs
some work(I have not gone through it very thoroughly)

I think whats best is to refocus our attention to _multi-sensor data fusion
using bayesian programming_
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=multi-sensor%20data%20fusion%20using%20bayesian%20programming%20an%20automotive%20application&es_th=1

read all the papers and article of this google search and follow the
citations etc if required, I suppose this is the best way to proceed and we
should stop beating around bushes now....please read all of them before
Tuesday, Wednesday ko discuss karte hai

**Comment by kishore19a** [comment]
parth, this book describes everything.....
https://books.google.co.in/books?id=HxjDMcJWLYwC&pg=PA44&lpg=PA44&dq=what+is+data+alignment+in+data+fusion&source=bl&ots=kcfw_0rfvu&sig=5q4XaV8-FqOQhV-paqbx82X9dLQ&hl=en&sa=X&ved=0CBwQ6AEwAGoVChMImKPo0P2CyAIVg5GOCh1E4ANz#v=onepage&q=what%20is%20data%20alignment%20in%20data%20fusion&f=false

**Comment by kishore19a** [comment]
<div>
Hello,

130020102 invited you to join MindSumo. Here is what they have to say about it:

Take a look at MindSumo - students solve problems for companies and win cash for good ideas. The experience and prizes are awesome. Check out https://www.mindsumo.com/?r=inH&su=164427&utm_campaign=website&utm_source=sendgrid.com&utm_medium=email Use my Promo Code while signing up: 1314B0E6

Go here http://bit.ly/1MLlUl9?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email to read more about it and sign up!

The MindSumo Team
